apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reddot
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: reddot-application
  source:
    repoURL: https://github.com/devops-g2/prodeploy.git
    targetRevision: HEAD
    path: .
    directory:
      recurse: true
    credentials:
      secretName: git-credentials
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
type: Opaque
stringData:
  username: dueweb
  password: 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
