apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reddit
spec:
  destination:
    name: acr-credentials
  source:
    repoURL: https://github.com/devops-g2/prodeploy.git
    targetRevision: HEAD
    path: .
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
