apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - traefik
  routes:
    - kind: Rule
      match: Host(`ip`) && PathPrefix(`/argocd`)
      priority: 10
      services:
        - name: my-argo-cd-argocd-server 
          port: 80
      #middlewares:
      #  - name: argocd-path-prefix
    - kind: Rule
      match: Host(`ip`) && Headers(`Content-Type`, `application/grpc`) && PathPrefix(`/argocd`)
      priority: 11
      services:
        - name: my-argo-cd-argocd-server
          port: 80
          scheme: h2c
