apiVersion: v1
kind: Secret
metadata:
  name: acr-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ZGV2MjJhY3I6aUhRNXJmZXBoL01FVHlvV3RyS1RIMDRpYlE5U3RpUFNvejFXOHIvQVR5K0FDUkJGTDZBSQ====
