apiVersion: v1
data:
  .dockerconfigjson: ${{ secrets.AZURECREDENTIALS }}
kind: Secret
metadata:
  labels: 
    argocd.argoproj.io/instance: reddit
  name: acr-credentials
type: kubernetes.io/dockerconfigjson
