apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkZXYyMmFjci5henVyZWNyLmlvIjogewoJCSAgInVzZXJuYW1lIjogImRldjIyYWNyIiwKCQkgICJwYXNzd29yZCI6ICJpSFE1cmZlcGgvTUVUeW9XdHJLVEgwNGliUTlTdGlQU296MVc4ci9BVHkrQUNSQkZMNkFJIiwKCQkgICJlbWFpbCI6ICJoYW1wdXMuZS5tb2xpbkBvdXRsb29rLmNvbSIsCgkJICAiYXV0aCI6ICJaR1YyTWpKaFkzSTZhVWhSTlhKbVpYQm9MMDFGVkhsdlYzUnlTMVJJTURScFlsRTVVM1JwVUZOdmVqRlhPSEl2UVZSNUswRkRVa0pHVERaQlNRPT0iCn0KCX0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4Igp9Cg==
kind: Secret
metadata:
  labels: 
    argocd.argoproj.io/instance: reddit
  name: acr-credentials
  namespace: reddit-application
type: kubernetes.io/dockerconfigjson
