apiVersion: v1
  data:
    .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkZXYyMmFjci5henVyZWNyLmlvIjoge30KCX0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4Igp9==
kind: Secret
metadata:
  labels: 
    argocd.argoproj.io/instance: reddit
  name: acr-credentials
  namespace: reddit-application
type: kubernetes.io/dockerconfigjson
