apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment-v1
  labels:
    app: service2-website
    component: website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service2-website
      component: website
      version: v1
  template:
    metadata:
      labels:
        app: service2-website
        component: website
        version: v1
    spec:
      containers:
        - name: service2-website
          imagePullPolicy: Always
          image: dev22acr.azurecr.io/website:latest
          ports:
            - containerPort: 5173
      imagePullSecrets:
        - name: dev22acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: service2-website
spec:
  type: ClusterIP
  selector:
    app: service2-website
    component: website
  ports:
    - port: 5173
      targetPort: 5173
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: service2-website-ingress
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`20.22.117.120`) 
      kind: Rule
      services:
        - name: service2-website
          port: 5173
