apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service2-api
    argocd.argoproj.io/instance: reddit
    component: api
  name: api-deployment-v1
  namespace: reddit-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service2-api
      component: api
      version: v1
  template:
    metadata:
      labels:
        app: service2-api
        component: api
        version: v1
    spec:
      containers:
        - image: 'dev22acr.azurecr.io/api:latest'
          imagePullPolicy: Always
          name: service2-api
          ports:
            - containerPort: 8001
      imagePullSecrets:
        - name: acr-credentials
---
apiVersion: v1
kind: Service
metadata:
  labels:
    argocd.argoproj.io/instance: reddit
  name: service2-api
  namespace: reddit-application
spec:
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: service2-api
    component: api
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
    argocd.argoproj.io/instance: reddit
  name: service2-api-ingress
  namespace: reddit-application
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`20.10.108.94`)
      services:
        - name: service2-api
          port: 8001
