apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingressroute
  namespace: prometheus-grafana
spec:
  entryPoints:
    - traefik
  routes:
    - match: Host(`20.10.108.94`) && PathPrefix (`/grafana/`)
      kind: Rule
      services:
        - name: prometheus-grafana
          port: 80
